name: Checks
on:
    push:
    pull_request:
        branches:
            - main
        types: [opened, synchronize, reopened]
jobs:
    checks:
        name: Run Checks
        runs-on: ubuntu-latest
        outputs:
            path: ${{ steps.insight.outputs.path }}
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
              with:
                  submodules: recursive
            - name: Setup Nix
              uses: cachix/install-nix-action@v27
              with:
                  nix_path: nixpkgs=channel:nixos-unstable
            - name: Checks
              run: nix-shell --run "make check"
            - id: insight
              run: |
                  FILE_PATH=$(cat .env | grep -Po "TYPST_FILE_PATH=\"\K([\w_/\-.]+)")
                  FILE_EXT=$(cat .env | grep -Po "TYPST_FILE_TYPE=\"\K([\w_/\-.]+)")
                  echo "$FILE_PATH"
                  echo "$FILE_EXT"
                  echo "path=${FILE_PATH}.${FILE_EXT}" >> "$GITHUB_OUTPUT"
    build:
        name: Build Document
        runs-on: ubuntu-latest
        needs: checks
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
              with:
                  submodules: recursive
            - name: Setup Nix
              uses: cachix/install-nix-action@v27
              with:
                  nix_path: nixpkgs=channel:nixos-unstable
            - name: Build
              run: nix-shell --run "make build"
            - name: Upload Artifact
              id: artifact-upload
              uses: actions/upload-artifact@v4
              with:
                  name: thesis-${{ github.sha }}
                  path: ${{ needs.checks.outputs.path }}
                  if-no-files-found: error
                  retention-days: 24
